import { LayoutConfig } from "../../types";
import { SkillBuilder } from "./SkillBuilder";
import { findMaxActiveRow, generateMosaics } from "./mosaics";
import { generateCentering } from "./centering";

export function generateSkillCode(config: LayoutConfig): string {
  const builder = new SkillBuilder();

  // ── File header ──────────────────────────────────────────────────────────
  builder.append(`
    ; ===================================================================
    ; Cadence SKILL Pixel Array Layout Generation Script
    ; AUTO GENERATED BY CADENCE SKILL PIXEL ARRAY LAYOUT GENERATOR
    ; Generated At: ${new Date().toISOString()}
    ; Author: Yongkai Zhang
    ; Copyright (c) ${new Date().getFullYear()} Yongkai Zhang
    ; ===================================================================
  `);

  // ── Procedure declaration + let variables ────────────────────────────────
  builder.append(`
    procedure(createPixelArray()
      let((
        cv
        master
        inst
        allInsts
        dx
        dy
        currentY
        maxActiveInst
        cx
        cy
        bBox
      )

      printf("\\n===============================\\n")
      printf("Pixel Array Generation Start\\n")
      printf("===============================\\n")

      ; Ensure target library exists
      unless(ddGetObj(
        "${config.top_lib}"
      )
        error(
          "Library ${config.top_lib} does not exist!\\n"
        )
      )

      ; Open the cell layout (create if it doesn't exist yet)
      if(ddGetObj(
        "${config.top_lib}"
        "${config.top_cell}"
        "layout"
      ) then
        printf(
          "Cellview ${config.top_cell} layout already exists. Opening...\\n"
        )
        cv = dbOpenCellViewByType(
          "${config.top_lib}"
          "${config.top_cell}"
          "layout"
          "maskLayout"
          "a"
        )
      else
        printf(
          "Cellview ${config.top_cell} layout does not exist. Creating new...\\n"
        )
        cv = dbOpenCellViewByType(
          "${config.top_lib}"
          "${config.top_cell}"
          "layout"
          "maskLayout"
          "w"
        )
      )

      when(cv == nil
        error("Cannot create or open target layout\\n")
      )

      unwindProtect(
        {
        ; Clear old instances and mosaics to prevent stacking when re-running
        when(cv
          foreach(inst cv~>instances
            dbDeleteObject(inst)
          )
          foreach(mosaic cv~>mosaics
            dbDeleteObject(mosaic)
          )
        )

        currentY = 0.0
        allInsts = nil
        rovInst = nil

  `);

  // ── Row mosaics + centering (filled in by sub-generators) ────────────────
  const maxActiveRow = findMaxActiveRow(config);
  generateMosaics(builder, config, maxActiveRow);
  generateCentering(builder, config);

  // ── Closing boilerplate ──────────────────────────────────────────────────
  builder.append(`
        }
        when(cv
          dbClose(cv)
        )
      )
      printf("\\nPixel Array Generation Complete!\\n")
    )
  )

  ; Execute procedure
  createPixelArray()
  `);

  return builder.build();
}
