import { LayoutConfig, RowConfig } from '../types';
import { getRowCategory } from '../math/grid';

export function generateSkillCode(config: LayoutConfig): string {
  const code: string[] = [];
  code.push('; ===================================================================');
  code.push('; Cadence SKILL Pixel Array Layout Generation Script');
  code.push('; AUTO GENERATED BY CADENCE SKILL PIXEL ARRAY LAYOUT GENERATOR');
  code.push(`; Generated At: ${new Date().toISOString()}`);
  code.push('; Author: Yongkai Zhang');
  code.push(`; Copyright (c) ${new Date().getFullYear()} Yongkai Zhang`);
  code.push('; ===================================================================');
  code.push('');
  code.push('procedure(createPixelArray()');
  code.push('  let((');
  code.push('    cv');
  code.push('    master');
  code.push('    inst');
  code.push('    allInsts');
  code.push('    dx');
  code.push('    dy');
  code.push('    currentY');
  code.push('  )');
  code.push('');
  code.push('    printf("\\n===============================\\n")');
  code.push('    printf("Pixel Array Generation Start\\n")');
  code.push('    printf("===============================\\n")');
  code.push('');
  code.push('    ; Ensure target library exists');
  code.push('    unless(ddGetObj(');
  code.push(`      "${config.top_lib}"`);
  code.push('    )');
  code.push('      error(');
  code.push(`        "Library ${config.top_lib} does not exist!\\n"`);
  code.push('      )');
  code.push('    )');
  code.push('');
  code.push('    ; Check if cell layout exists. If so open it, otherwise create it.');
  code.push('    if(ddGetObj(');
  code.push(`      "${config.top_lib}"`);
  code.push(`      "${config.top_cell}"`);
  code.push('      "layout"');
  code.push('    ) then');
  code.push('      printf(');
  code.push(`        "Cellview ${config.top_cell} layout already exists. Opening...\\n"`);
  code.push('      )');
  code.push('      cv = dbOpenCellViewByType(');
  code.push(`        "${config.top_lib}"`);
  code.push(`        "${config.top_cell}"`);
  code.push('        "layout"');
  code.push('        "maskLayout"');
  code.push('        "a"');
  code.push('      )');
  code.push('    else');
  code.push('      printf(');
  code.push(`        "Cellview ${config.top_cell} layout does not exist. Creating new...\\n"`);
  code.push('      )');
  code.push('      cv = dbOpenCellViewByType(');
  code.push(`        "${config.top_lib}"`);
  code.push(`        "${config.top_cell}"`);
  code.push('        "layout"');
  code.push('        "maskLayout"');
  code.push('        "w"');
  code.push('      )');
  code.push('    )');
  code.push('');
  code.push('    when(cv == nil');
  code.push('      error("Cannot create or open target layout\\n")');
  code.push('    )');
  code.push('');
  code.push('    unwindProtect(');
  code.push('      {');
  code.push('    ; Clear old instances and mosaics to prevent stacking when re-running');
  code.push('    when(cv');
  code.push('      foreach(inst cv~>instances');
  code.push('        dbDeleteObject(inst)');
  code.push('      )');
  code.push('      foreach(mosaic cv~>mosaics');
  code.push('        dbDeleteObject(mosaic)');
  code.push('      )');
  code.push('    )');
  code.push('');
  code.push('    currentY = 0.0');
  code.push('    allInsts = nil');
  code.push('    rovInst = nil');
  code.push('');

  // 1. Identify the true active block with the maximum row count
  let maxActiveRow: RowConfig | null = null;
  config.rows.forEach(row => {
    const isAct = getRowCategory(row.purpose, row.name || '', config.rov_purpose) === 'active';
    if (isAct) {
      if (!maxActiveRow || row.rows > maxActiveRow.rows) {
        maxActiveRow = row;
      }
    }
  });

    // Iterate rows backwards (bottom→top) to match Cadence viewport (+Y is UP)
  const reversedRows = [...config.rows].reverse();
  reversedRows.forEach((row, rev_idx) => {
    const orig_idx = config.rows.length - 1 - rev_idx;
    const row_num = orig_idx + 1;
    const purpose = row.purpose;
    const rowName = row.name || purpose;

    const cleanPurpose = purpose.toLowerCase().replace(/[^a-zA-Z0-9_]/g, '_');
    const mosaicName = `M${row_num}_${cleanPurpose}`;

    code.push(`  ; --- Creating ${rowName} Rows ---`);
    code.push('  printf(');
    code.push(`    "Creating ${rowName} (purpose: ${purpose}) rows=${row.rows} y=%L\\n"`);
    code.push('    currentY');
    code.push('  )');
    code.push('');

    if (!row.segments || row.segments.length === 0) {
      const cellInfo = config.cell_map[purpose.toLowerCase()];
      code.push('  master =');
      code.push('    dbOpenCellViewByType(');
      code.push(`      "${cellInfo.lib}"`);
      code.push(`      "${cellInfo.cell}"`);
      code.push('      "layout"');
      code.push('      "maskLayout"');
      code.push('      "r"');
      code.push('    )');
      code.push('');
      code.push('  when(');
      code.push('    master == nil');
      code.push('    error(');
      code.push(`      "Cannot open master ${cellInfo.cell}\\n"`);
      code.push('    )');
      code.push('  )');
      code.push('');
      code.push(`  inst = dbCreateSimpleMosaic(`);
      code.push('    cv');
      code.push('    master');
      code.push(`    "${mosaicName}"`);
      code.push('    list(0.0 0.0)');
      code.push('    "R180"');
      code.push(`    ${row.rows}`);
      code.push(`    ${config.total_cols}`);
      code.push(`    ${config.y_pitch}`);
      code.push(`    ${config.x_pitch}`);
      code.push('  )');
      code.push('  unless(inst');
      code.push(`    inst = dbCreateMosaic(`);
      code.push('      cv');
      code.push('      master');
      code.push(`      "${mosaicName}"`);
      code.push('      list(0.0 0.0)');
      code.push('      "R180"');
      code.push(`      ${row.rows}`);
      code.push(`      ${config.total_cols}`);
      code.push(`      ${config.y_pitch}`);
      code.push(`      ${config.x_pitch}`);
      code.push('    )');
      code.push('  )');
      code.push('');
      code.push('  when(');
      code.push('    inst == nil');
      code.push('    error(');
      code.push(`      "Failed creating ${purpose}\\n"`);
      code.push('    )');
      code.push('  )');
      code.push('');
      code.push('  when(inst');
      code.push(`    dx = ${config.total_cols} * ${config.x_pitch}`);
      code.push(`    dy = currentY + (${row.rows} * ${config.y_pitch})`);
      code.push('    inst~>xy = list(dx dy)');
      code.push('  )');
      code.push('');
      code.push('  allInsts =');
      code.push('    cons(');
      code.push('      list(inst "R180")');
      code.push('      allInsts');
      code.push('    )');
      code.push('');
      
      const isRov = purpose.toLowerCase() === config.rov_purpose.toLowerCase();
      if (isRov && row === maxActiveRow) {
        code.push('  printf("ACTIVE MOSAIC FOUND\\n")');
      }
    } else {
      let currSegX = 0.0;
      row.segments.forEach((seg, sIdx) => {
        const segPurpose = seg.purpose;
        const segCols = seg.cols;
        const cleanSegPurpose = segPurpose.toLowerCase().replace(/[^a-zA-Z0-9_]/g, '_');
        const segMosaicName = `M${row_num}_${cleanPurpose}_seg${sIdx + 1}_${cleanSegPurpose}`;
        
        let segCellInfo = config.cell_map[segPurpose.toLowerCase()];
        if (!segCellInfo) {
          segCellInfo = {
            name: segPurpose,
            lib: 'pixel_lib',
            cell: `cell_${segPurpose}`,
            rot: 'R0'
          };
        }

        code.push(`  ; Segment ${sIdx + 1}: ${segPurpose} (cols=${segCols})`);
        code.push('  master =');
        code.push('    dbOpenCellViewByType(');
        code.push(`      "${segCellInfo.lib}"`);
        code.push(`      "${segCellInfo.cell}"`);
        code.push('      "layout"');
        code.push('      "maskLayout"');
        code.push('      "r"');
        code.push('    )');
        code.push('');
        code.push('  when(');
        code.push('    master == nil');
        code.push('    error(');
        code.push(`      "Cannot open master ${segCellInfo.cell}\\n"`);
        code.push('    )');
        code.push('  )');
        code.push('');
        code.push(`  inst = dbCreateSimpleMosaic(`);
        code.push('    cv');
        code.push('    master');
        code.push(`    "${segMosaicName}"`);
        code.push('    list(0.0 0.0)');
        code.push('    "R180"');
        code.push(`    ${row.rows}`);
        code.push(`    ${segCols}`);
        code.push(`    ${config.y_pitch}`);
        code.push(`    ${config.x_pitch}`);
        code.push('  )');
        code.push('  unless(inst');
        code.push(`    inst = dbCreateMosaic(`);
        code.push('      cv');
        code.push('      master');
        code.push(`      "${segMosaicName}"`);
        code.push('      list(0.0 0.0)');
        code.push('      "R180"');
        code.push(`      ${row.rows}`);
        code.push(`      ${segCols}`);
        code.push(`      ${config.y_pitch}`);
        code.push(`      ${config.x_pitch}`);
        code.push('    )');
        code.push('  )');
        code.push('');
        code.push('  when(');
        code.push('    inst == nil');
        code.push('    error(');
        code.push(`      "Failed creating segment ${segPurpose}\\n"`);
        code.push('    )');
        code.push('  )');
        code.push('');
        code.push('  when(inst');
        code.push(`    dx = ${currSegX.toFixed(4)} + (${segCols} * ${config.x_pitch})`);
        code.push('    dy = currentY + (' + row.rows + ' * ' + config.y_pitch + ')');
        code.push('    inst~>xy = list(dx dy)');
        code.push('  )');
        code.push('');
        code.push('  allInsts =');
        code.push('    cons(');
        code.push('      list(inst "R180")');
        code.push('      allInsts');
        code.push('    )');
        code.push('');
        
        const isRov = segPurpose.toLowerCase() === config.rov_purpose.toLowerCase();
        if (isRov && row === maxActiveRow) {
          code.push('  printf("ACTIVE SEGMENT MOSAIC FOUND\\n")');
        }
        
        currSegX += segCols * config.x_pitch;
      });
    }

    code.push(`    currentY = currentY + (${row.rows} * ${config.y_pitch})`);
    code.push('');
  });

  // Calculate true geometric center of the ROV active block
  let firstActiveIdx = -1;
  let lastActiveIdx = -1;
  config.rows.forEach((row, idx) => {
    const isAct = getRowCategory(row.purpose, row.name || '', config.rov_purpose) === 'active' || getRowCategory(row.purpose, row.name || '', config.rov_purpose) === 'rov';
    if (isAct) {
      if (firstActiveIdx === -1) firstActiveIdx = idx;
      lastActiveIdx = idx;
    }
  });

  let left_cols = 0;
  let active_cols = config.total_cols;
  
  // Find the exact ROV segment by strictly matching rov_purpose to ignore paddings
  const rovRow = config.rows.find(r => r.segments && r.segments.some(s => s.purpose.toLowerCase() === config.rov_purpose.toLowerCase()));
  if (rovRow && rovRow.segments) {
    const activeSegIdx = rovRow.segments.findIndex(s => s.purpose.toLowerCase() === config.rov_purpose.toLowerCase());
    for (let i = 0; i < activeSegIdx; i++) {
      left_cols += rovRow.segments[i].cols;
    }
    active_cols = rovRow.segments[activeSegIdx].cols;
  } else if (firstActiveIdx !== -1) {
    // Fallback if no exact match
    const firstActiveRow = config.rows[firstActiveIdx];
    if (firstActiveRow.segments && firstActiveRow.segments.length > 0) {
      const activeSegIdx = firstActiveRow.segments.findIndex(s => getRowCategory(s.purpose, '', config.rov_purpose) === 'active');
      if (activeSegIdx !== -1) {
        for (let i = 0; i < activeSegIdx; i++) {
          left_cols += firstActiveRow.segments[i].cols;
        }
        active_cols = firstActiveRow.segments[activeSegIdx].cols;
      }
    }
  }
  // With R180 rotation, the mosaic's physical lower-left is at (origin.x - cols*xPitch, origin.y - rows*yPitch).
  // We place origin at (currSegX + segCols*xPitch, currentY + rows*yPitch) so LL lands at (currSegX, currentY).
  // For the centering calculation, the physical left edge of the ROV content is at:
  //   left_physical_x = left_cols * x_pitch
  // And the physical center X of the ROV content is:
  //   center_x = (left_cols + active_cols/2) * x_pitch
  // We want center_x + targetDx = 0, so targetDx = -(left_cols + active_cols/2) * x_pitch
  // BUT: since each mosaic origin is at (segCols*xPitch + currSegX), the actual content X range is
  //   [currSegX, currSegX + segCols*xPitch]
  // So the centering math below remains the same (left_cols in column units, active_cols in column units).
  const targetDx = - (config.total_cols / 2.0) * config.x_pitch;

  let startY_rows = 0;
  let endY_rows = 0;
  let maxActiveIdx = -1;
  let maxRows = 0;
  config.rows.forEach((row, idx) => {
    const isAct = getRowCategory(row.purpose, row.name || '', config.rov_purpose) === 'active' || getRowCategory(row.purpose, row.name || '', config.rov_purpose) === 'rov';
    if (isAct && row.rows > maxRows) {
      maxRows = row.rows;
      maxActiveIdx = idx;
    }
  });

  if (maxActiveIdx !== -1) {
    for (let i = maxActiveIdx + 1; i < config.rows.length; i++) {
      startY_rows += config.rows[i].rows;
    }
    endY_rows = startY_rows + config.rows[maxActiveIdx].rows;
  }

  const targetDy = (maxActiveIdx !== -1)
    ? - (startY_rows + endY_rows) / 2.0 * config.y_pitch
    : - (config.rows.reduce((sum, r) => sum + r.rows, 0) / 2.0) * config.y_pitch;

  code.push('    ; --- Center Array at (0, 0) ---');
  code.push('    printf("\\nFinding Global Array Center...\\n")');
  code.push(`    dx = ${targetDx.toFixed(4)}`);
  code.push(`    dy = ${targetDy.toFixed(4)}`);
  code.push('    printf("Global Center: cx=%L cy=%L\\n" 0.0 - dx 0.0 - dy)');
  code.push('    printf("Shifting all parts by dx=%L dy=%L\\n" dx dy)');
  code.push('');
  code.push('    foreach(item allInsts');
  code.push('      inst = car(item)');
  code.push('      inst~>xy = list(car(inst~>xy) + dx cadr(inst~>xy) + dy)');
  code.push('    )');
  code.push('');
  code.push('    ; --- Rotations applied during creation ---');
  code.push('');
  code.push('    dbSave(cv)');
  code.push('      }');
  code.push('      when(cv');
  code.push('        dbClose(cv)');
  code.push('      )');
  code.push('    )');
  code.push('    printf("\\nPixel Array Generation Complete!\\n")');
  code.push('  )');
  code.push(')');
  code.push('');
  code.push('; Execute procedure');
  code.push('createPixelArray()');

  return code.join('\n');
}
